version: 2.1
orbs:
  docker: circleci/docker@0.5.19
  helm-tools: pennlabs/helm-tools@0.1.10

branch-filters: &branch-filters
  filters:
    branches:
      only:
        - master

jobs:
  test:
    working_directory: ~/pennlabs
    docker:
      - image: circleci/node:10
        environment:
          MONGO_URI: mongodb://127.0.0.1:27017/data
      - image: circleci/mongo:4.2.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ~/.cache/npm
      # - run:
      #     name: Lint
      #     command: |
      #       npm run lint

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - docker/publish:
          requires:
            - test
          image: pennlabs/penn-basics
          tag: "$CIRCLE_SHA1,latest"
          context: docker-publish
          <<: *branch-filters
      - helm-tools/deploy:
          requires:
            - docker/publish
          context: k8s-deploy
          <<: *branch-filters
