deploy_version: 0.1.0
image_tag: latest

applications:
  - name: basics
    image: pennlabs/pennbasics
    secret: basics
    ingress:
      hosts:
        - host: pennbasics.com
          paths: ["/"]