deploy_version: 0.1.20
image_tag: latest

applications:
  - name: react
    image: pennlabs/penn-basics
    secret: penn-basics
    extraEnv:
      - name: PORT
        value: 80
    ingress:
      hosts:
        - host: pennbasics.com
          paths: ["/"]
