deploy_version: 0.1.8
image_tag: latest

applications:
  - name: basics
    image: pennlabs/pennbasics
    secret: basics
    extraEnv:
      - name: PORT
        value: 80
    ingress:
      hosts:
        - host: pennbasics.com
          paths: ["/"]