apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
{{ if .Values.staging }}
  namespace: staging
{{- end }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
  selector:
    name: {{ .Release.Name }}
