name: Build and Deploy
on: push
jobs:
  react:
    name: React
    uses: pennlabs/shared-actions/.github/workflows/react.yaml@v0.1.9
    with:
      imageName: penn-basics
      path: .
      githubRef: ${{ github.ref }}
      skipReactCheck: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  deployment:
    name: Deploy
    uses: pennlabs/shared-actions/.github/workflows/deployment.yaml@v0.1.9
    with:
      githubRef: ${{ github.ref }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      GH_AWS_ACCESS_KEY_ID: ${{ secrets.GH_AWS_ACCESS_KEY_ID }}
      GH_AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_AWS_SECRET_ACCESS_KEY }}
    needs:
      - react
